# @package _global_

module:
  _target_: emg2qwerty.lightning.CNNBiLSTMCTCModule

  # If freq=33: 2 * 16 * 33 = 1056
  in_features: 1056

  cnn_layers_count: 2
  cnn_channels1: 128
  cnn_channels2: 256
  cnn_kernel_size: 5
  cnn_stride: 1

  lstm_hidden: 256
  lstm_layers: 2
  dropout: 0.2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]